// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjd13mlcAMPdTcAzjTzyqTyTphR6S3A6w',
    appId: '1:120727932135:web:18d6f449536a80f2196642',
    messagingSenderId: '120727932135',
    projectId: 'xploreeats',
    authDomain: 'xploreeats.firebaseapp.com',
    storageBucket: 'xploreeats.appspot.com',
    measurementId: 'G-3PPZ1EDT4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHbyKjsMM-KAemCx-G8vfF4HungExHc2U',
    appId: '1:120727932135:android:fa292fa77d006d5d196642',
    messagingSenderId: '120727932135',
    projectId: 'xploreeats',
    storageBucket: 'xploreeats.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv4KWBI9A_hW0YC5uPbRz0t1OZbRVnIBQ',
    appId: '1:120727932135:ios:ffe7195835926de5196642',
    messagingSenderId: '120727932135',
    projectId: 'xploreeats',
    storageBucket: 'xploreeats.appspot.com',
    iosClientId: '120727932135-cfh7rkl9vivt6jt9iiju81vv82jlektm.apps.googleusercontent.com',
    iosBundleId: 'com.heyidb.xploreeats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv4KWBI9A_hW0YC5uPbRz0t1OZbRVnIBQ',
    appId: '1:120727932135:ios:ffe7195835926de5196642',
    messagingSenderId: '120727932135',
    projectId: 'xploreeats',
    storageBucket: 'xploreeats.appspot.com',
    iosClientId: '120727932135-cfh7rkl9vivt6jt9iiju81vv82jlektm.apps.googleusercontent.com',
    iosBundleId: 'com.heyidb.xploreeats',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjd13mlcAMPdTcAzjTzyqTyTphR6S3A6w',
    appId: '1:120727932135:web:b308d68e22dfba42196642',
    messagingSenderId: '120727932135',
    projectId: 'xploreeats',
    authDomain: 'xploreeats.firebaseapp.com',
    storageBucket: 'xploreeats.appspot.com',
    measurementId: 'G-JLNTW6EK74',
  );

}